"[#] ci/cd":
 - '.github/*'
 - '.github/**/*'

"[#] deps":
 - 'go.mod'
 - 'go.sum'

"[#] doc":
 - '*.md'
 - 'doc/*'
 - 'doc/**/*'
 - 'examples/*'
 - 'examples/**/*'
 - 'internal/**/*'

"[#] ring":
 - '*.go'
